using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyTitleAttribute("Apache NMS for ActiveMQ Class Library")]
[assembly: AssemblyDescriptionAttribute("Apache NMS for ActiveMQ Class Library (.Net Messaging Library Implementation): An" +
    " implementation of the NMS API for ActiveMQ")]
[assembly: AssemblyConfigurationAttribute("GA")]
[assembly: AssemblyCompanyAttribute("http://activemq.apache.org/nms")]
[assembly: AssemblyProductAttribute("Apache NMS for ActiveMQ Class Library")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2005-2012 Apache Software Foundation")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("1.5.0.2586")]
[assembly: AssemblyInformationalVersionAttribute("1.5.0")]

